version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - /storage/docker/postgresql-datadir:/var/lib/postgresql
